// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDAyCkMRjtojMbQH62KFAkTzk6dA5ZcZM',
    appId: '1:287312614993:web:e4096ed8376e78de4c0a70',
    messagingSenderId: '287312614993',
    projectId: 'mymoai-19b3c',
    authDomain: 'mymoai-19b3c.firebaseapp.com',
    storageBucket: 'mymoai-19b3c.appspot.com',
    measurementId: 'G-0QK6X1TXYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbXR1VWkPGgWECWswsM_ko0Qiv3oNvor4',
    appId: '1:287312614993:android:0f1f95f3aab915474c0a70',
    messagingSenderId: '287312614993',
    projectId: 'mymoai-19b3c',
    storageBucket: 'mymoai-19b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmqtYjF_Q5PE4bp1kktRJ8jOqTt8iJ04',
    appId: '1:287312614993:ios:7fbeb352269582db4c0a70',
    messagingSenderId: '287312614993',
    projectId: 'mymoai-19b3c',
    storageBucket: 'mymoai-19b3c.appspot.com',
    iosBundleId: 'com.example.mymoai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmqtYjF_Q5PE4bp1kktRJ8jOqTt8iJ04',
    appId: '1:287312614993:ios:ed3504d315553add4c0a70',
    messagingSenderId: '287312614993',
    projectId: 'mymoai-19b3c',
    storageBucket: 'mymoai-19b3c.appspot.com',
    iosBundleId: 'com.example.mymoai.RunnerTests',
  );
}
